// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: captcha.proto
#ifndef GRPC_captcha_2eproto__INCLUDED
#define GRPC_captcha_2eproto__INCLUDED

#include "captcha.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace CAPTCHA_RPC {

class Captcha final {
 public:
  static constexpr char const* service_full_name() {
    return "CAPTCHA_RPC.Captcha";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::CAPTCHA_RPC::CaptchaJson* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::CaptchaJson>> AsyncGetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::CaptchaJson>>(AsyncGetCaptchaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::CaptchaJson>> PrepareAsyncGetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::CaptchaJson>>(PrepareAsyncGetCaptchaRaw(context, request, cq));
    }
    virtual ::grpc::Status VerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::CAPTCHA_RPC::Status* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::Status>> AsyncVerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::Status>>(AsyncVerifyCaptchaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::Status>> PrepareAsyncVerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::Status>>(PrepareAsyncVerifyCaptchaRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty* request, ::CAPTCHA_RPC::CaptchaJson* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::CaptchaJson* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty* request, ::CAPTCHA_RPC::CaptchaJson* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty* request, ::CAPTCHA_RPC::CaptchaJson* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::CaptchaJson* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::CaptchaJson* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void VerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson* request, ::CAPTCHA_RPC::Status* response, std::function<void(::grpc::Status)>) = 0;
      virtual void VerifyCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::Status* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void VerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson* request, ::CAPTCHA_RPC::Status* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void VerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson* request, ::CAPTCHA_RPC::Status* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void VerifyCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::Status* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void VerifyCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::Status* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::CaptchaJson>* AsyncGetCaptchaRaw(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::CaptchaJson>* PrepareAsyncGetCaptchaRaw(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::Status>* AsyncVerifyCaptchaRaw(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CAPTCHA_RPC::Status>* PrepareAsyncVerifyCaptchaRaw(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::CAPTCHA_RPC::CaptchaJson* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::CaptchaJson>> AsyncGetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::CaptchaJson>>(AsyncGetCaptchaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::CaptchaJson>> PrepareAsyncGetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::CaptchaJson>>(PrepareAsyncGetCaptchaRaw(context, request, cq));
    }
    ::grpc::Status VerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::CAPTCHA_RPC::Status* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::Status>> AsyncVerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::Status>>(AsyncVerifyCaptchaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::Status>> PrepareAsyncVerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::Status>>(PrepareAsyncVerifyCaptchaRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty* request, ::CAPTCHA_RPC::CaptchaJson* response, std::function<void(::grpc::Status)>) override;
      void GetCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::CaptchaJson* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty* request, ::CAPTCHA_RPC::CaptchaJson* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty* request, ::CAPTCHA_RPC::CaptchaJson* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::CaptchaJson* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::CaptchaJson* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void VerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson* request, ::CAPTCHA_RPC::Status* response, std::function<void(::grpc::Status)>) override;
      void VerifyCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::Status* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void VerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson* request, ::CAPTCHA_RPC::Status* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void VerifyCaptcha(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson* request, ::CAPTCHA_RPC::Status* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void VerifyCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::Status* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void VerifyCaptcha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::CAPTCHA_RPC::Status* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::CaptchaJson>* AsyncGetCaptchaRaw(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::CaptchaJson>* PrepareAsyncGetCaptchaRaw(::grpc::ClientContext* context, const ::CAPTCHA_RPC::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::Status>* AsyncVerifyCaptchaRaw(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::CAPTCHA_RPC::Status>* PrepareAsyncVerifyCaptchaRaw(::grpc::ClientContext* context, const ::CAPTCHA_RPC::CaptchaJson& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetCaptcha_;
    const ::grpc::internal::RpcMethod rpcmethod_VerifyCaptcha_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetCaptcha(::grpc::ServerContext* context, const ::CAPTCHA_RPC::Empty* request, ::CAPTCHA_RPC::CaptchaJson* response);
    virtual ::grpc::Status VerifyCaptcha(::grpc::ServerContext* context, const ::CAPTCHA_RPC::CaptchaJson* request, ::CAPTCHA_RPC::Status* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCaptcha() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::Empty* /*request*/, ::CAPTCHA_RPC::CaptchaJson* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCaptcha(::grpc::ServerContext* context, ::CAPTCHA_RPC::Empty* request, ::grpc::ServerAsyncResponseWriter< ::CAPTCHA_RPC::CaptchaJson>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VerifyCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VerifyCaptcha() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_VerifyCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::CaptchaJson* /*request*/, ::CAPTCHA_RPC::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyCaptcha(::grpc::ServerContext* context, ::CAPTCHA_RPC::CaptchaJson* request, ::grpc::ServerAsyncResponseWriter< ::CAPTCHA_RPC::Status>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetCaptcha<WithAsyncMethod_VerifyCaptcha<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetCaptcha() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::CAPTCHA_RPC::Empty, ::CAPTCHA_RPC::CaptchaJson>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::CAPTCHA_RPC::Empty* request, ::CAPTCHA_RPC::CaptchaJson* response) { return this->GetCaptcha(context, request, response); }));}
    void SetMessageAllocatorFor_GetCaptcha(
        ::grpc::experimental::MessageAllocator< ::CAPTCHA_RPC::Empty, ::CAPTCHA_RPC::CaptchaJson>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::CAPTCHA_RPC::Empty, ::CAPTCHA_RPC::CaptchaJson>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::Empty* /*request*/, ::CAPTCHA_RPC::CaptchaJson* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetCaptcha(
      ::grpc::CallbackServerContext* /*context*/, const ::CAPTCHA_RPC::Empty* /*request*/, ::CAPTCHA_RPC::CaptchaJson* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetCaptcha(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::CAPTCHA_RPC::Empty* /*request*/, ::CAPTCHA_RPC::CaptchaJson* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_VerifyCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_VerifyCaptcha() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::CAPTCHA_RPC::CaptchaJson, ::CAPTCHA_RPC::Status>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::CAPTCHA_RPC::CaptchaJson* request, ::CAPTCHA_RPC::Status* response) { return this->VerifyCaptcha(context, request, response); }));}
    void SetMessageAllocatorFor_VerifyCaptcha(
        ::grpc::experimental::MessageAllocator< ::CAPTCHA_RPC::CaptchaJson, ::CAPTCHA_RPC::Status>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::CAPTCHA_RPC::CaptchaJson, ::CAPTCHA_RPC::Status>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_VerifyCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::CaptchaJson* /*request*/, ::CAPTCHA_RPC::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* VerifyCaptcha(
      ::grpc::CallbackServerContext* /*context*/, const ::CAPTCHA_RPC::CaptchaJson* /*request*/, ::CAPTCHA_RPC::Status* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* VerifyCaptcha(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::CAPTCHA_RPC::CaptchaJson* /*request*/, ::CAPTCHA_RPC::Status* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetCaptcha<ExperimentalWithCallbackMethod_VerifyCaptcha<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetCaptcha<ExperimentalWithCallbackMethod_VerifyCaptcha<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCaptcha() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::Empty* /*request*/, ::CAPTCHA_RPC::CaptchaJson* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VerifyCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VerifyCaptcha() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_VerifyCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::CaptchaJson* /*request*/, ::CAPTCHA_RPC::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCaptcha() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::Empty* /*request*/, ::CAPTCHA_RPC::CaptchaJson* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCaptcha(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_VerifyCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VerifyCaptcha() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_VerifyCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::CaptchaJson* /*request*/, ::CAPTCHA_RPC::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyCaptcha(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetCaptcha() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCaptcha(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::Empty* /*request*/, ::CAPTCHA_RPC::CaptchaJson* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetCaptcha(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetCaptcha(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_VerifyCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_VerifyCaptcha() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->VerifyCaptcha(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_VerifyCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::CaptchaJson* /*request*/, ::CAPTCHA_RPC::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* VerifyCaptcha(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* VerifyCaptcha(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCaptcha() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CAPTCHA_RPC::Empty, ::CAPTCHA_RPC::CaptchaJson>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::CAPTCHA_RPC::Empty, ::CAPTCHA_RPC::CaptchaJson>* streamer) {
                       return this->StreamedGetCaptcha(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::Empty* /*request*/, ::CAPTCHA_RPC::CaptchaJson* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCaptcha(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CAPTCHA_RPC::Empty,::CAPTCHA_RPC::CaptchaJson>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VerifyCaptcha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_VerifyCaptcha() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CAPTCHA_RPC::CaptchaJson, ::CAPTCHA_RPC::Status>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::CAPTCHA_RPC::CaptchaJson, ::CAPTCHA_RPC::Status>* streamer) {
                       return this->StreamedVerifyCaptcha(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_VerifyCaptcha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VerifyCaptcha(::grpc::ServerContext* /*context*/, const ::CAPTCHA_RPC::CaptchaJson* /*request*/, ::CAPTCHA_RPC::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerifyCaptcha(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CAPTCHA_RPC::CaptchaJson,::CAPTCHA_RPC::Status>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetCaptcha<WithStreamedUnaryMethod_VerifyCaptcha<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetCaptcha<WithStreamedUnaryMethod_VerifyCaptcha<Service > > StreamedService;
};

}  // namespace CAPTCHA_RPC


#endif  // GRPC_captcha_2eproto__INCLUDED
